/**
 * @file Automatically generated by @tsed/barrels.
 */
export * from "./OrdersController/Controller.js";
export * from "./OrdersController/Services.js";
export * from "./ProductsController/Controller.js";
export * from "./ProductsController/Services.js";
export * from "./UsersController/Controller.js";
export * from "./UsersController/Services.js";
